<ChatsScreen>:
    BoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Чаты"
            left_action_items: [["menu", lambda x: root.open_menu(x)]]
        ScrollView:
            MDList:
                id: chats_list
        MDFloatingActionButton:
            icon: "plus"
            pos_hint: {"right": 0.95, "bottom": 0.05}
            on_release: root.create_new_chat()
