name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pre-download Android NDK
      run: |
        echo "Downloading Android NDK..."
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -O ndk.zip
        unzip -q ndk.zip -d ndk
        mkdir -p ~/.buildozer/android/platform/
        mv ndk/android-ndk-r21e ~/.buildozer/android/platform/android-ndk-r21e
        echo "Android NDK installed successfully."

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged -v ${{ github.workspace }}:/app:z -v /tmp:/tmp
        run: |
          # Копируем проект в рабочую директорию
          mkdir -p /tmp/app
          cp -r /app/* /tmp/app/
          cd /tmp/app
          
          # Устанавливаем окружение Buildozer
          export BUILDOZER_HOME=/tmp/.buildozer_home
          mkdir -p $BUILDOZER_HOME
          chmod -R 777 $BUILDOZER_HOME
          
          # Принудительное использование NDK r21e
          echo "Setting custom NDK path..."
          sed -i 's/android-ndk-r25b/android-ndk-r21e/' ~/.buildozer/android/platform/android-ndk-r21e/source.properties

          # Отключение загрузки NDK через Buildozer
          sed -i 's/self._install_android_ndk/#self._install_android_ndk/' /home/user/.local/lib/python3.8/site-packages/buildozer/targets/android.py

          # Сборка APK
          echo "Starting Buildozer..."
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: /tmp/app/bin/*.apk
