name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged
        run: |
          echo "Checking current directory..."
          pwd
          echo "Listing files..."
          ls -la
          echo "Changing directory to /github/workspace..."
          cd /github/workspace || exit 1
          echo "Checking files again..."
          ls -la
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk
