name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pre-download Android NDK
      run: |
        echo "Downloading Android NDK..."
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -O ndk.zip
        unzip -q ndk.zip -d android-ndk
        echo "Android NDK downloaded and extracted."

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged -v ${{ github.workspace }}:/app:z -v /tmp:/tmp
        run: |
          # Копируем проект в временную директорию
          mkdir -p /tmp/app
          cp -r /app/* /tmp/app/
          cp -r /app/android-ndk/android-ndk-r21e /tmp/.buildozer/android/platform/
          cd /tmp/app
          
          # Устанавливаем окружение Buildozer
          export BUILDOZER_HOME=/tmp/.buildozer_home
          mkdir -p $BUILDOZER_HOME
          chmod -R 777 $BUILDOZER_HOME
          
          # Сборка APK
          echo "Starting Buildozer..."
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: /tmp/app/bin/*.apk
