name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged -v ${{ github.workspace }}:/app:z
        run: |
          echo "Changing to /app..."
          cd /app
          echo "Creating a writable directory..."
          export BUILDOZER_HOME=/tmp/.buildozer_home
          mkdir -p $BUILDOZER_HOME
          chmod -R 777 $BUILDOZER_HOME
          echo "Starting Buildozer..."
          BUILDOZER_GLOBAL_OPTIONS="--build-dir=$BUILDOZER_HOME" buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: /app/bin/*.apk
