name: Build APK

on:
  push:
    branches:
      - master # Или другая ветка, например main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-11-jdk
        pip install buildozer cython

    - name: Check Buildozer spec
      run: |
        if [ ! -f buildozer.spec ]; then
          echo "Error: buildozer.spec not found!"
          exit 1
        fi

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged -v ${{ github.workspace }}:/app:z -v /tmp:/tmp
        run: |
          # Копируем проект в временную папку
          mkdir -p /tmp/app
          cp -r /app/* /tmp/app/
          cd /tmp/app
          # Создаем Buildozer окружение
          export BUILDOZER_HOME=/tmp/.buildozer_home
          mkdir -p $BUILDOZER_HOME
          chmod -R 777 $BUILDOZER_HOME
          # Стартуем Buildozer
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: /tmp/app/bin/*.apk
