name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged -v ${{ github.workspace }}:/app:z -v /tmp:/tmp
        run: |
          echo "Changing to /app..."
          cd /app
          echo "Setting up writable directories..."
          export BUILDOZER_HOME=/tmp/.buildozer_home
          export ANDROID_NDK_HOME=/tmp/android-ndk
          mkdir -p $BUILDOZER_HOME
          mkdir -p $ANDROID_NDK_HOME
          chmod -R 777 $BUILDOZER_HOME $ANDROID_NDK_HOME
          echo "Increasing HTTP timeout..."
          export BUILDOZER_HTTP_TIMEOUT=300
          echo "Starting Buildozer..."
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: /app/bin/*.apk
