name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged -v ${{ github.workspace }}:/app:z -v /tmp:/tmp
        run: |
          # Устанавливаем рабочую директорию
          mkdir -p /tmp/app
          cp -r /app/* /tmp/app/
          cd /tmp/app

          # Устанавливаем Android NDK вручную
          echo "Downloading and installing Android NDK..."
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip -O /tmp/android-ndk.zip
          unzip -q /tmp/android-ndk.zip -d /tmp/android-ndk
          mv /tmp/android-ndk/android-ndk-r25b ~/.buildozer/android/platform/android-ndk-r25b
          echo "NDK installation complete."

          # Устанавливаем Buildozer окружение
          export BUILDOZER_HOME=/tmp/.buildozer_home
          mkdir -p $BUILDOZER_HOME
          chmod -R 777 $BUILDOZER_HOME

          # Запускаем Buildozer
          echo "Starting Buildozer..."
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: /tmp/app/bin/*.apk
