name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged --user 1000:1000 -v ${{ github.workspace }}:/app
        run: |
          echo "Changing to /app..."
          cd /app
          echo "Setting up temporary Buildozer directory..."
          export BUILDOZER_HOME=/home/user/.buildozer
          mkdir -p $BUILDOZER_HOME
          echo "Starting Buildozer..."
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk
