name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK using Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: --privileged
        run: |
          export SUPABASE_URL=${SUPABASE_URL}
          export SUPABASE_KEY=${SUPABASE_KEY}
          export CLOUDAMQP_URL=${CLOUDAMQP_URL}
          buildozer -v android debug
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        CLOUDAMQP_URL: ${{ secrets.CLOUDAMQP_URL }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk
